### ISSUE TITLE
Unused consumes all processing resources often leading to computer hang or automatic restart

### ISSUE THREAD

**Issue by ctoynbee** [joshuaclayton/unused#107]
Just wondering if anyone else is having an issue where running unused uses all available resources and usually results in either hanging the computer or the operating system restarting itself?

I've tried using: 

`sudo nice -n -20 unused `

but it does not have any effect.

I left unused running over night to see if it would finish during an 8 - 10 hour window but the computer was unresponsive in the morning and had to be restarted.

My installation steps were:

```
brew tap joshuaclayton/formulae
brew install unused
git ls-files | xargs ctags
```

When I start the program it states:

`Unused: analyzing 5883 terms`

Then it usually hangs the computer.

I've also tried:

`sudo nice -n -20 unused -C`

I'm running macOS 1015.3

I have this version installed: joshuaclayton/formulae/unused 0.10.0.0

I've also added the .unused.yml file to my root directory from here:

https://github.com/joshuaclayton/unused#user-content-unusedyml

I'm running a rails app. Happy to give more details on the application if needed.

**Comment by joshuaclayton** [comment]
@ctoynbee yes, this is a known issue with this version of Unused. I'm wrapping up a complete rewrite in Rust that is much more memory-efficient and reduces execution time to a trivial amount for most moderately-sized codebases. Since I won't be addressing the performance issues in this repo, I'm closing this issue out.
