### ISSUE TITLE
Rails validators are falsely detected as unused

### ISSUE THREAD

**Issue by r00k** [joshuaclayton/unused#18]
I have an `AbsoluteUriValidator`.

`unused` thinks it's unused, but it's not.

Usage looks like `validates :webhook_url, absolute_uri: true`.

**Comment by joshuaclayton** [comment]
@r00k so I understand, the token it's complaining about is `AbsoluteUriValidator` (and not `absolute_uri`), correct?

Thoughts on how to handle this?

**Comment by r00k** [comment]
Yep.

![screen shot 2016-05-16 at 11 25 17 am](https://cloud.githubusercontent.com/assets/46677/15294114/e6ba8a96-1b58-11e6-95e9-bcce795b53e2.png)

You might just want to special-case this particular Rails "magic".

**Comment by r00k** [comment]
`FooBarValidator` is used if you see `validates foo_bar: true`.

**Comment by r00k** [comment]
Although, there's probably a million of these special cases for Rails. No idea if you want to try to chase a bunch of them down :).

**Comment by joshuaclayton** [comment]
I want to look at projections.vim again and see how they handle transformations of wording - might be of interest. I agree that unused itself should manage this, although a set of recommended configs (assuming configs would be used for this sort of thing) would be nice.

**Comment by joshuaclayton** [comment]
@MattMSumner and I spoke about this on Friday, and while our original takeaway was that because ctags doesn't capture the symbol (when the validator is being used), one could (eventually) use a custom config to ignore validators.

That said, I think that actually goes against the goal of this tool, which is to help identify dead code - so even though ctags doesn't catch it, with an alias, we'd be able to (this is the same case for implied matchers in RSpec, like `have_`, since they're not formally defined ctags won't pick them up).

Once basic wildcard swaps are supported, I imagine we'd be able to add transformations to this fairly easily. After looking at some other tools, we could go a couple routes:

string formatting, e.g.

```
%S: Snake-case the match
%c: lower camel-case the match
%C: upper camel-case the match
```

or some sort of chainable vocabulary:

```
%s{singularize|tableize|constantize}
```

where that vocabulary is documented.

String formatting might be the way to go right now, since it won't require a custom parser and effectively makes it harder to mess up, but it's less composable. I think it should cover most cases, especially in Rails.
