### ISSUE TITLE
Ruby writer methods are reported as unused

### ISSUE THREAD

**Issue by mrageh** [joshuaclayton/unused#61]
Hey Joshua

Thanks for creating this fantastic library!

When I ran `unused` on our rails app at work it would report ruby writer methods as defined only. 
This is probably because the way we define writer methods and use them in Ruby is slightly different.

Example writer method:

```
def writer=(arg)
end
```

Example use of writer method:

```
writer = some_arg
```

Perhaps this is something that can be improved within `unused`?

**Comment by joshuaclayton** [comment]
@mrageh apologies for the late reply - as it turns out, I wasn't getting notified when issues were created here!

I've noticed similar issues on my projects. The tricky aspect is Rails *also* allows for assignment via a hash for anything ActiveModel-like: `Thing.new(writer: "Of course it is!")`.

Would you be interested in beta-testing a configuration change to see how it works out for you over the coming few weeks?

I outline custom configurations [here](https://github.com/joshuaclayton/unused#unusedyml). If you haven't already configured `~/.unused.yml`, perfect! We're just going to add a few lines:

```
- name: Rails
  aliases:
    - from: "*="
      to: "{}:"
    - from: "*="
      to: ".{} ="
```

This should cover both cases (hash and attribute assignment), although it might be a bit liberal in matching. The first alias covers converting `writer_name=` into `writer_name:`, while the second converts it to `.writer_name =`. This ensures that it's not capturing local variable assignment.

If this works for you, it might make sense to either fold into the default Rails config, or include it in an example file (being discussed here: https://github.com/joshuaclayton/unused/issues/66).

Looking forward to hearing how this goes for you!

**Comment by mrageh** [comment]
> Would you be interested in beta-testing a configuration change to see how it works out for you over the coming few weeks?

Yes I'd be interested in beta-testing this config change, I'll let you know how it goes.

**Comment by joshuaclayton** [comment]
@mrageh how's this been going? Any thoughts on this approach?

**Comment by mrageh** [comment]
Hey @joshuaclayton 

Unfortunately the custom configurations did not work for me.

Did the custom configurations only work on Rails projects or Ruby projects as well?

**Comment by joshuaclayton** [comment]
@mrageh it should work across both Ruby and Rails projects.

One thing on my docket is to allow a way to remove cache files. If you run `unused -C` (which skips the cache), does it subsequently work?

**Comment by mrageh** [comment]
@joshuaclayton This is the command I've executed `cat tags | unused -C --stdin` and `unused` does not associate writer methods with all the times they're called.
