### ISSUE TITLE
Unused is unaware of `alias_method_chain`

### ISSUE THREAD

**Issue by sgrif** [joshuaclayton/unused#62]
While it's now deprecated, it's still somewhat common in older codebases. Seems like it'd make sense for any token matching `(.*)_with_(.*)` to search for `alias_method_chain :\1, :\2` as well

**Comment by joshuaclayton** [comment]
@sgrif this is actually a lot trickier to handle than the current alias mechanism, since it only matches one wildcard. I'd based it on the syntax of [projectionist](https://github.com/tpope/vim-projectionist) in order to do transformations, so there's no way to do multiple capture groups.

Especially given it's deprecated, I'm going to close this for now. If there are a handful of other multi-wildcard aliases that crop up, though, I may have to come up with a way to address this.
