### ISSUE TITLE
How long is this supposed to take to install?

### ISSUE THREAD

**Issue by williamcodes** [joshuaclayton/unused#78]
I've been installing with brew and it's been like a half hour. Looks like it's still installing Haskell. Does it normally take that long to install or is it hung? If it's really that slow, could we add something to the troubleshooting section that warns installation could take a long time if Haskell has never been installed before? It might save some future souls some angst.

**Comment by joshuaclayton** [comment]
@williamcodes installation time depends on previous installed software, along with the capabilities of the machine itself. On my machine (late-2013 MBP), it takes about four minutes to install from Homebrew. I could see it printing out a message from the Homebrew formula when prepping for installation to let everyone know it might take a while, although I'm not sure if Homebrew suggests that or not.

I haven't dug too deeply but I might try to understand how to get onto Homebrew proper (instead of running my own tap) and having them compile binaries. In the meantime, I added the binary to https://github.com/joshuaclayton/unused/releases/tag/v0.6.1.1 this morning. If you're interested in trying to use the binary from there, please let me know how it works and what OS you're on.

Interested in opening up a PR to the README with a note under the installation that because it needs to compile, installation times may vary but that it's often a handful of minutes?
