### ISSUE TITLE
Provide a macports port

### ISSUE THREAD

**Issue by ajm188** [joshuaclayton/unused#88]
As an alternative installation option, being able to install via MacPorts would be **awesome**.

I can try to look into this over the next few days and see what that would involve.

**Comment by joshuaclayton** [comment]
@ajm188 I'm not opposed to that, although I don't know what goes into it or what would need to be maintained, and because I don't use MacPorts, I also don't think it makes sense for me to maintain it. If you're interested in looking into it and think it'd be preferred to installing via stack, that seems good to me.

**Comment by ajm188** [comment]
I'm new to supporting MacPorts as well (long-time user, first time author and all that). I did a bit of reading, and it seems pretty straightforward, mostly just going to be a thin wrapper around the stack commands, from what I can tell so far.

I'll try to whip up a PR quickly - if you don't think it's worth maintaining, then that's fine, too. It's your repo 😄

**Comment by ajm188** [comment]
By the way, here is the mega-doc I'm going to base these changes off of: https://guide.macports.org/chunked/reference.phases.html

**Comment by joshuaclayton** [comment]
Given any associated maintenance "costs", I'm going to close this. If Macports has a mechanism similar to Homebrew (e.g. `brew tap`), I'd be happy to include a link.
